import '../models/scheme.dart';
import '../models/channel_partner.dart';
import '../models/user.dart';
import '../models/application.dart';

class MockDataService {
  static UserProfile get defaultUser => UserProfile(
    id: 'usr_demo',
    name: 'Ravi Kumar',
    phone: '9876543210',
    email: 'ravi.kumar@example.com',
    age: 28,
    category: 'OBC',
    annualIncome: 240000,
    businessType: 'Food Business',
    experienceYears: 2,
    location: UserLocation(
      latitude: 17.3850,
      longitude: 78.4867,
      city: 'Hyderabad',
      state: 'Telangana',
    ),
    savedSchemes: ['sch_1'],
  );

  static List<Scheme> get mockSchemes => [
    Scheme(
      id: 'sch_1',
      schemeName: 'PM Mudra Yojana',
      shortCode: 'PMMY',
      category: 'Central Government',
      tagline: 'Funding the Unfunded - Collateral Free Micro Loans',
      description: 'Pradhan Mantri Mudra Yojana (PMMY) provides loans up to ₹10 Lakh to non-corporate, non-farm small/micro enterprises. Divided into Shishu (up to ₹50k), Kishore (₹50k to ₹5L), and Tarun (₹5L to ₹10L).',
      maxGrantLoanAmount: 1000000,
      loanAmountFormatted: 'Up to ₹10,00,000',
      interestRate: '8% - 12% (approx.)',
      interestRateNumeric: 9.5,
      repaymentPeriod: 'Up to 5 Years',
      repaymentPeriodYears: 5,
      minAge: 18,
      maxIncome: 0,
      eligibleCategories: ['All', 'General', 'OBC', 'SC', 'ST', 'Women Entrepreneur'],
      eligibleBusinessTypes: ['Food Business', 'Retail / Kirana Shop', 'Handicrafts & Handlooms', 'Manufacturing & Fabrication'],
      minExperienceYears: 0,
      subsidyPercentage: 0,
      whoCanApply: 'Micro & Small Enterprises',
      purpose: 'Business Expansion, Working Capital, New Business',
      benefits: [
        '100% Collateral-free loan with zero processing fee for Shishu',
        'Flexible repayment tenure up to 5 years',
        'Mudra Debit Card issued for daily working capital withdrawal'
      ],
      requiredDocuments: [
        SchemeDocument(docName: 'Aadhaar Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'PAN Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'Business Plan', status: 'Pending', isMandatory: false),
        SchemeDocument(docName: 'Bank Statement', status: 'Pending', isMandatory: false),
        SchemeDocument(docName: 'Address Proof', status: 'Uploaded', isMandatory: true),
      ],
      tags: ['Low Interest', 'Easy Process', 'Collateral-Free'],
      matchPercentage: 90,
      matchBadge: '90% Match',
      highlightTag: 'Top Choice',
      eligibilityReasons: [
        'Meets age requirement (18-70 years)',
        'Eligible for OBC category',
        'Eligible for Food Business activity'
      ],
    ),
    Scheme(
      id: 'sch_2',
      schemeName: 'PMEGP Scheme',
      shortCode: 'PMEGP',
      category: 'Central Government',
      tagline: 'Prime Minister Employment Generation Programme with up to 35% Subsidy',
      description: 'Credit-linked subsidy programme to generate self-employment micro-enterprises in non-farm sector with government subsidy of 15% to 35%.',
      maxGrantLoanAmount: 2500000,
      loanAmountFormatted: 'Up to ₹25,00,000',
      interestRate: '9% - 11% (approx.)',
      interestRateNumeric: 10.0,
      repaymentPeriod: 'Up to 7 Years',
      repaymentPeriodYears: 7,
      minAge: 18,
      maxIncome: 0,
      eligibleCategories: ['OBC', 'SC', 'ST', 'Women Entrepreneur', 'General'],
      eligibleBusinessTypes: ['Manufacturing & Fabrication', 'Food Business', 'Agriculture & Allied'],
      minExperienceYears: 0,
      subsidyPercentage: 35,
      whoCanApply: 'Individuals above 18 years, SHGs, Co-operatives',
      purpose: 'Setting up new business micro-enterprises',
      benefits: [
        'Government subsidy of 25% to 35% for rural & special category (OBC/SC/ST)',
        'Bank credit for 90% to 95% of project cost',
        'Free Entrepreneurship Development Training (EDP)'
      ],
      requiredDocuments: [
        SchemeDocument(docName: 'Aadhaar Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'PAN Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'Caste Certificate', status: 'Pending', isMandatory: true),
        SchemeDocument(docName: 'Project Report (DPR)', status: 'Pending', isMandatory: true),
      ],
      tags: ['For New Business', 'High Subsidy (35%)', 'Govt Grant'],
      matchPercentage: 85,
      matchBadge: '85% Match',
      highlightTag: 'High Subsidy',
      eligibilityReasons: [
        'Meets age requirement (18-70 years)',
        'OBC category receives 35% subsidy benefit',
        'Food Processing sector recognized'
      ],
    ),
    Scheme(
      id: 'sch_3',
      schemeName: 'Stand Up India Scheme',
      shortCode: 'SUIS',
      category: 'Central Government',
      tagline: 'Empowering SC, ST, and Women Entrepreneurs with Greenfield Credit',
      description: 'Facilitates bank credit between ₹10 Lakh and ₹1 Crore to SC/ST and Women entrepreneurs for setting up greenfield manufacturing, service or trading ventures.',
      maxGrantLoanAmount: 10000000,
      loanAmountFormatted: 'Loan from ₹10L to ₹1Cr',
      interestRate: '8% - 10% (concessional)',
      interestRateNumeric: 8.75,
      repaymentPeriod: 'Up to 7 Years',
      repaymentPeriodYears: 7,
      minAge: 18,
      maxIncome: 0,
      eligibleCategories: ['SC', 'ST', 'Women Entrepreneur', 'OBC'],
      eligibleBusinessTypes: ['Food Business', 'Manufacturing & Fabrication', 'Retail / Kirana Shop', 'Services / Repair Shop'],
      minExperienceYears: 1,
      subsidyPercentage: 15,
      whoCanApply: 'SC/ST and/or Women Entrepreneurs',
      purpose: 'Greenfield commercial business setup',
      benefits: [
        'High ticket size up to ₹1 Crore',
        'Moratorium period up to 18 months',
        'SIDBI institutional handholding'
      ],
      requiredDocuments: [
        SchemeDocument(docName: 'Aadhaar Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'PAN Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'Project Proposal', status: 'Pending', isMandatory: true),
      ],
      tags: ['For SC/ST & Women', 'Loan ₹10L to ₹1Cr'],
      matchPercentage: 75,
      matchBadge: '75% Match',
      highlightTag: 'High Credit Limit',
      eligibilityReasons: [
        'Meets age requirement (18-70 years)',
        'Recognized sector for greenfield financing'
      ],
    ),
    Scheme(
      id: 'sch_4',
      schemeName: 'PMFME Scheme',
      shortCode: 'PMFME',
      category: 'Central Government',
      tagline: '35% Capital Subsidy for Food Processing Micro-Enterprises',
      description: 'Pradhan Mantri Formalisation of Micro food processing Enterprises scheme provides 35% credit-linked capital subsidy up to ₹10 Lakh for upgrading food units, bakeries, and tiffin processing centers.',
      maxGrantLoanAmount: 1000000,
      loanAmountFormatted: 'Up to ₹10,00,000 (35% Subsidy)',
      interestRate: '8.5% - 10.5%',
      interestRateNumeric: 9.0,
      repaymentPeriod: 'Up to 7 Years',
      repaymentPeriodYears: 7,
      minAge: 18,
      maxIncome: 0,
      eligibleCategories: ['All', 'General', 'OBC', 'SC', 'ST', 'Women Entrepreneur'],
      eligibleBusinessTypes: ['Food Business'],
      minExperienceYears: 0,
      subsidyPercentage: 35,
      whoCanApply: 'Food Processing Units, Bakeries, Canteens, FPOs, SHGs',
      purpose: 'Food Processing Plant, Bakery Equipment, Modern Machinery',
      benefits: [
        '35% credit-linked capital subsidy up to ₹10 Lakh',
        'FSSAI registration & food safety compliance support',
        'Technical training and branding assistance'
      ],
      requiredDocuments: [
        SchemeDocument(docName: 'Aadhaar Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'PAN Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'FSSAI License / Application', status: 'Pending', isMandatory: false),
        SchemeDocument(docName: 'Machinery Quotation', status: 'Pending', isMandatory: true),
      ],
      tags: ['35% Subsidy', 'Food Processing', 'Bakery & Tiffin'],
      matchPercentage: 95,
      matchBadge: '95% Match',
      highlightTag: 'Food Sector Special',
      eligibilityReasons: [
        'Dedicated scheme for Food Processing enterprises',
        'Eligible for 35% capital subsidy'
      ],
    ),
    Scheme(
      id: 'sch_5',
      schemeName: 'PM SVANidhi',
      shortCode: 'PM-SVANIDHI',
      category: 'Central Government',
      tagline: 'Collateral-free working capital loan for Street Vendors with 7% interest subsidy',
      description: 'Special micro-credit facility for street vendors and pushcart owners providing ₹10,000, ₹20,000, and ₹50,000 progressive working capital loans with 7% interest subvention and UPI cashback.',
      maxGrantLoanAmount: 50000,
      loanAmountFormatted: '₹10,000 to ₹50,000',
      interestRate: '7% Interest Subsidy (Effective ~4%)',
      interestRateNumeric: 4.5,
      repaymentPeriod: '1 to 3 Years',
      repaymentPeriodYears: 1,
      minAge: 18,
      maxIncome: 0,
      eligibleCategories: ['All', 'General', 'OBC', 'SC', 'ST', 'Differently Abled (Divyangjan)'],
      eligibleBusinessTypes: ['Street Vending'],
      minExperienceYears: 0,
      subsidyPercentage: 7,
      whoCanApply: 'Street Vendors, Pushcart Owners, Roadside Hawkers with Vending Certificate or Letter of Recommendation',
      purpose: 'Daily Inventory, Fruit/Veggie Procurement, Pushcart upgrade',
      benefits: [
        '100% Collateral-free micro-credit without any bank security',
        '7% interest subsidy credited directly to bank account on timely repayment',
        'Up to ₹1,200/year cashback on digital UPI transactions',
        'Tranche progression: ₹10k -> ₹20k -> ₹50k on timely repayment'
      ],
      requiredDocuments: [
        SchemeDocument(docName: 'Aadhaar Card (Mobile Linked)', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'Vending Certificate / Urban Local Body LOR', status: 'Pending', isMandatory: true),
        SchemeDocument(docName: 'Bank Passbook / UPI QR Code', status: 'Uploaded', isMandatory: true),
      ],
      tags: ['No Collateral', '7% Subsidy', 'Instant UPI Cashback'],
      matchPercentage: 95,
      matchBadge: '95% Match',
      highlightTag: 'Street Vendor Dedicated',
      eligibilityReasons: [
        'Specifically designed for street vendors and pushcarts',
        'Includes 7% interest subsidy & UPI cashback'
      ],
    ),
    Scheme(
      id: 'sch_6',
      schemeName: 'PM Vishwakarma Scheme',
      shortCode: 'PM-VISHWAKARMA',
      category: 'Central Government',
      tagline: 'Empowering Traditional Artisans with ₹15,000 Toolkit Incentive & 5% Subsidized Loan',
      description: 'Central sector scheme for 18 traditional artisan trades (carpenters, blacksmiths, potters, tailors, sculptors). Provides ₹15,000 modern toolkit grant and up to ₹3 Lakh collateral-free loan at 5% interest.',
      maxGrantLoanAmount: 300000,
      loanAmountFormatted: 'Up to ₹3,00,000 (at 5% Interest)',
      interestRate: '5% Fixed (8% Govt Subvention)',
      interestRateNumeric: 5.0,
      repaymentPeriod: '18 to 30 Months',
      repaymentPeriodYears: 3,
      minAge: 18,
      maxIncome: 0,
      eligibleCategories: ['All', 'General', 'OBC', 'SC', 'ST', 'Differently Abled (Divyangjan)'],
      eligibleBusinessTypes: ['Handicrafts & Handlooms', 'Textile & Garments'],
      minExperienceYears: 0,
      subsidyPercentage: 8,
      whoCanApply: 'Artisans and craftspersons engaged in one of 18 trades (Tailor, Weaver, Carpenter, Blacksmith, Potter, Sculptor)',
      purpose: 'Modern Artisan Toolkits, Workshop Modernization, Working Capital',
      benefits: [
        '₹15,000 digital e-voucher grant for modern toolkits',
        'Collateral-free enterprise loan up to ₹3 Lakh at just 5% interest (Tranche 1: ₹1L, Tranche 2: ₹2L)',
        'Basic 5-7 days and advanced 15+ days skill training with ₹500/day stipend',
        'Official PM Vishwakarma ID card and digital recognition certificate'
      ],
      requiredDocuments: [
        SchemeDocument(docName: 'Aadhaar Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'Trade Certificate / Gram Panchayat Verification', status: 'Pending', isMandatory: true),
        SchemeDocument(docName: 'Bank Account Passbook', status: 'Uploaded', isMandatory: true),
      ],
      tags: ['5% Interest', '₹15,000 Toolkit Grant', 'Govt Certified'],
      matchPercentage: 95,
      matchBadge: '95% Match',
      highlightTag: 'Artisan Dedicated',
      eligibilityReasons: [
        'Tailored specifically for artisans and traditional craftsmen',
        'Includes ₹15k toolkit grant and 5% concessional credit'
      ],
    ),
    Scheme(
      id: 'sch_7',
      schemeName: 'Weaver Mudra Scheme',
      shortCode: 'WEAVER-MUDRA',
      category: 'Central Government',
      tagline: 'Concessional Handloom Weaver Credit up to ₹2 Lakh @ 6% with ₹25,000 Margin Money Grant',
      description: 'Concessional credit scheme for handloom weavers and allied workers. Provides loans up to ₹2 Lakh at 6% interest rate with margin money assistance up to ₹25,000 and credit guarantee coverage.',
      maxGrantLoanAmount: 200000,
      loanAmountFormatted: 'Up to ₹2,00,000 (@ 6% Interest)',
      interestRate: '6% Concessional (Govt Subvention)',
      interestRateNumeric: 6.0,
      repaymentPeriod: '3 Years',
      repaymentPeriodYears: 3,
      minAge: 18,
      maxIncome: 0,
      eligibleCategories: ['All', 'General', 'OBC', 'SC', 'ST', 'Women Entrepreneur'],
      eligibleBusinessTypes: ['Handicrafts & Handlooms'],
      minExperienceYears: 0,
      subsidyPercentage: 20,
      whoCanApply: 'Handloom weavers, master weavers, handloom cooperatives and allied workers',
      purpose: 'Raw material procurement (yarn, dye), handloom loom upgrade, working capital',
      benefits: [
        'Concessional interest rate of 6% to weavers (subvention up to 7%)',
        'Margin money assistance of 20% of project cost (up to ₹25,000)',
        '100% Credit guarantee coverage by CGTMSE with zero collateral',
        'Direct yarn subsidy linkage via National Handloom Development Programme (NHDP)'
      ],
      requiredDocuments: [
        SchemeDocument(docName: 'Aadhaar Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'Weaver Pehchan Card / Handloom Identity Card', status: 'Pending', isMandatory: true),
        SchemeDocument(docName: 'Bank Passbook', status: 'Uploaded', isMandatory: true),
      ],
      tags: ['6% Interest', '₹25,000 Margin Grant', 'Weaver Dedicated'],
      matchPercentage: 92,
      matchBadge: '92% Match',
      highlightTag: 'Handloom Exclusive',
      eligibilityReasons: [
        'Dedicated financial support for handloom weavers',
        'Margin money grant up to ₹25,000 with 6% interest'
      ],
    ),
    Scheme(
      id: 'sch_8',
      schemeName: 'Kisan Credit Card',
      shortCode: 'KCC',
      category: 'Central Government',
      tagline: '4% Subsidized Institutional Credit for Crop Production, Dairy Farming & Allied Agri',
      description: 'Comprehensive revolving credit line for farmers, dairy owners, and allied agriculture with prompt repayment incentive reducing effective interest rate to just 4% per annum up to ₹3 Lakh.',
      maxGrantLoanAmount: 300000,
      loanAmountFormatted: 'Up to ₹3,00,000 (@ 4% Net Rate)',
      interestRate: '4% (with 3% prompt repayment incentive)',
      interestRateNumeric: 4.0,
      repaymentPeriod: '1 Year (Revolving 5-Year Facility)',
      repaymentPeriodYears: 1,
      minAge: 18,
      maxIncome: 0,
      eligibleCategories: ['All', 'General', 'OBC', 'SC', 'ST'],
      eligibleBusinessTypes: ['Agriculture & Allied'],
      minExperienceYears: 0,
      subsidyPercentage: 3,
      whoCanApply: 'Owner cultivators, tenant farmers, dairy farmers, poultry owners, aquaculture operators',
      purpose: 'Crop cultivation expenses, cattle purchase, dairy feed, tractor maintenance',
      benefits: [
        'Effective interest rate of only 4% per annum for loans up to ₹3 Lakh',
        'Collateral-free agricultural loans up to ₹1.60 Lakh',
        'Flexible drawdowns via ATM-enabled RuPay Kisan Credit Card',
        'Includes natural calamity crop insurance coverage under PMFBY'
      ],
      requiredDocuments: [
        SchemeDocument(docName: 'Aadhaar Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'Land Record (Pattadar Passbook / 1-B / Tenancy Agreement)', status: 'Pending', isMandatory: true),
        SchemeDocument(docName: 'Crop Declaration / Cattle Ownership Proof', status: 'Pending', isMandatory: true),
      ],
      tags: ['4% Interest', 'Kisan RuPay Card', 'Agri & Dairy'],
      matchPercentage: 94,
      matchBadge: '94% Match',
      highlightTag: 'Agriculture Top Choice',
      eligibilityReasons: [
        'Dedicated scheme for agriculture and dairy operations',
        'Subsidized 4% interest rate on timely repayment'
      ],
    ),
    Scheme(
      id: 'sch_9',
      schemeName: 'SAMARTH Textile Scheme',
      shortCode: 'SAMARTH-TEXTILE',
      category: 'Central Government',
      tagline: 'Skill Development & Entrepreneurial Linkage for Garment, Apparel & Tailoring Units',
      description: 'Flagship scheme under Ministry of Textiles providing wage employment and self-employment skilling, machinery linkage, and subsidized capital support for garment manufacturing and apparel boutiques.',
      maxGrantLoanAmount: 500000,
      loanAmountFormatted: 'Up to ₹5,00,000 (Skilling + Machine Credit)',
      interestRate: '7% - 9%',
      interestRateNumeric: 8.0,
      repaymentPeriod: 'Up to 5 Years',
      repaymentPeriodYears: 5,
      minAge: 18,
      maxIncome: 0,
      eligibleCategories: ['All', 'Women Entrepreneur', 'OBC', 'SC', 'ST', 'General'],
      eligibleBusinessTypes: ['Textile & Garments'],
      minExperienceYears: 0,
      subsidyPercentage: 25,
      whoCanApply: 'Tailoring boutiques, garment manufacturers, apparel micro-units, women textile SHGs',
      purpose: 'Industrial sewing machines, computer embroidery machines, garment boutique inventory',
      benefits: [
        'NSQF-aligned certified skill training in modern apparel design & production',
        'Subsidized machine acquisition linkage through partnered textile banks',
        'Special 75% reservation preference for women, SC, ST, and Divyangjan',
        'Market linkage and direct orders assistance with garment exporters and retail chains'
      ],
      requiredDocuments: [
        SchemeDocument(docName: 'Aadhaar Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'PAN Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'Garment Machine Quotation', status: 'Pending', isMandatory: false),
      ],
      tags: ['Textile & Apparel', 'Modern Tailoring', 'Women Priority'],
      matchPercentage: 92,
      matchBadge: '92% Match',
      highlightTag: 'Garment Dedicated',
      eligibilityReasons: [
        'Specialized for tailoring, garments, and textile boutiques',
        'High women entrepreneur preference & machinery linkage'
      ],
    ),
    Scheme(
      id: 'sch_10',
      schemeName: 'MSME Sustainable ZED Scheme',
      shortCode: 'MSME-ZED',
      category: 'Central Government',
      tagline: 'Up to 80% Government Subsidy for Technology Upgradation & Zero Defect Manufacturing',
      description: 'Ministry of MSME incentive scheme for manufacturing and fabrication units providing up to 80% subsidy for Bronze, Silver, and Gold certification, modern equipment testing, and clean technology upgrades.',
      maxGrantLoanAmount: 5000000,
      loanAmountFormatted: 'Up to ₹50,00,000 (Up to 80% Subsidy)',
      interestRate: '8.0% - 10.0%',
      interestRateNumeric: 8.5,
      repaymentPeriod: 'Up to 7 Years',
      repaymentPeriodYears: 7,
      minAge: 18,
      maxIncome: 0,
      eligibleCategories: ['All', 'General', 'OBC', 'SC', 'ST', 'Women Entrepreneur'],
      eligibleBusinessTypes: ['Manufacturing & Fabrication'],
      minExperienceYears: 0,
      subsidyPercentage: 80,
      whoCanApply: 'Micro, small, and medium manufacturing and fabrication enterprises holding Udyam Registration',
      purpose: 'Zero Defect Zero Effect manufacturing upgrade, CNC machines, precision tools, quality testing',
      benefits: [
        'Up to 80% subsidy on certification costs and technology assessment',
        'Up to ₹5 Lakh financial assistance for testing and clean technology equipment',
        '0.5% interest rate concession on bank loans for ZED-certified MSMEs',
        'Preferential scoring in government and public procurement tenders'
      ],
      requiredDocuments: [
        SchemeDocument(docName: 'Udyam Registration Certificate', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'PAN Card & Aadhaar Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'Factory / Workshop Electricity Bill', status: 'Pending', isMandatory: true),
      ],
      tags: ['Up to 80% Subsidy', 'Manufacturing', 'Technology Upgrade'],
      matchPercentage: 93,
      matchBadge: '93% Match',
      highlightTag: 'Manufacturing Dedicated',
      eligibilityReasons: [
        'Targeted for fabrication and manufacturing workshops',
        'Up to 80% subsidy on technology upgrades'
      ],
    ),
    Scheme(
      id: 'sch_11',
      schemeName: 'PMEGP Service & Transport',
      shortCode: 'PMEGP-SERVICE',
      category: 'Central Government',
      tagline: 'Up to ₹20 Lakh Project Loan with 35% Capital Subsidy for Service Centers & Transport',
      description: 'PMEGP service sector variant for auto repair garages, heavy vehicle maintenance shops, diagnostic centers, and commercial transport ventures with up to 35% margin money subsidy.',
      maxGrantLoanAmount: 2000000,
      loanAmountFormatted: 'Up to ₹20,00,000 (35% Subsidy)',
      interestRate: '9% - 11%',
      interestRateNumeric: 9.5,
      repaymentPeriod: 'Up to 7 Years',
      repaymentPeriodYears: 7,
      minAge: 18,
      maxIncome: 0,
      eligibleCategories: ['All', 'General', 'OBC', 'SC', 'ST', 'Differently Abled (Divyangjan)'],
      eligibleBusinessTypes: ['Services / Repair Shop'],
      minExperienceYears: 0,
      subsidyPercentage: 35,
      whoCanApply: 'Mechanics, technicians, garage owners, auto service centers, commercial drivers',
      purpose: 'Vehicle diagnostic equipment, hydraulic lifts, repair toolkits, commercial vehicles',
      benefits: [
        '25% (urban) to 35% (rural/special category) government non-repayable subsidy',
        'Bank loan covers 90% to 95% of total project cost',
        'Free 10-day Entrepreneurship Development Programme (EDP) certification',
        'Moratorium period up to 6 months during garage setup'
      ],
      requiredDocuments: [
        SchemeDocument(docName: 'Aadhaar Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'PAN Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'Driving License / Mechanic Trade Certificate', status: 'Pending', isMandatory: false),
        SchemeDocument(docName: 'Detailed Project Report (DPR)', status: 'Pending', isMandatory: true),
      ],
      tags: ['35% Subsidy', 'Repair & Garage', 'Commercial Transport'],
      matchPercentage: 94,
      matchBadge: '94% Match',
      highlightTag: 'Services Top Pick',
      eligibilityReasons: [
        'Specially structured for repair workshops and service garages',
        'Up to 35% capital subsidy on project cost'
      ],
    ),
    Scheme(
      id: 'sch_12',
      schemeName: 'Divyangjan Swavalamban Yojana',
      shortCode: 'NHFDC-DSY',
      category: 'Central Government',
      tagline: 'Concessional Self-Employment Loans at 4% - 8% for Persons with Disabilities (PwD)',
      description: 'National Handicapped Finance and Development Corporation scheme providing concessional loans up to ₹50 Lakh for Persons with Disabilities (40%+ disability) for starting any commercial venture with 0.5% - 1% extra rebate for women.',
      maxGrantLoanAmount: 5000000,
      loanAmountFormatted: 'Up to ₹50,00,000 (at 4% - 8%)',
      interestRate: '4% - 8% (Concessional for PwD)',
      interestRateNumeric: 5.0,
      repaymentPeriod: 'Up to 10 Years',
      repaymentPeriodYears: 7,
      minAge: 18,
      maxIncome: 0,
      eligibleCategories: ['Differently Abled (Divyangjan)'],
      eligibleBusinessTypes: ['Food Business', 'Retail / Kirana Shop', 'Handicrafts & Handlooms', 'Agriculture & Allied', 'Textile & Garments', 'Manufacturing & Fabrication', 'Services / Repair Shop', 'Street Vending'],
      minExperienceYears: 0,
      subsidyPercentage: 35,
      whoCanApply: 'Persons with Disabilities (PwD) with 40% or more disability and valid UDID card',
      purpose: 'Self-employment in any micro-enterprise, shop, vehicle, or manufacturing setup',
      benefits: [
        'Concessional interest rate starting from 4% per annum',
        'Additional 0.5% - 1% interest rebate for women entrepreneurs with disabilities',
        'Repayment tenure up to 10 years with flexible moratorium up to 12 months',
        'Financial assistance for assistive devices and accessible workplace modifications'
      ],
      requiredDocuments: [
        SchemeDocument(docName: 'UDID Card / Disability Certificate (40%+)', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'Aadhaar Card', status: 'Uploaded', isMandatory: true),
        SchemeDocument(docName: 'Project Quotation / Business Proposal', status: 'Pending', isMandatory: true),
      ],
      tags: ['Divyangjan Exclusive', '4% - 8% Low Rate', 'Up to ₹50 Lakh'],
      matchPercentage: 98,
      matchBadge: '98% Match',
      highlightTag: 'Divyangjan Special',
      eligibilityReasons: [
        'Exclusive scheme for persons with disabilities (40%+)',
        'Highly concessional interest rate (4%-8%) with 10-year tenure'
      ],
    ),
  ];

  static List<ChannelPartner> get mockPartners => [
    ChannelPartner(
      id: 'ptn_1',
      partnerName: 'Andhra Grameena Bank',
      type: 'Bank',
      address: 'Koti Main Road, Beside Post Office, Hyderabad',
      latitude: 17.3880,
      longitude: 78.4890,
      contactPhone: '+91 40 2475 8890',
      contactPerson: 'Srinivasa Rao (Branch Manager)',
      distanceKm: 0.8,
      rating: 4.8,
    ),
    ChannelPartner(
      id: 'ptn_2',
      partnerName: 'KVK Business Center',
      type: 'KVK',
      address: 'PJTSAU Campus, Rajendranagar, Hyderabad',
      latitude: 17.3780,
      longitude: 78.4750,
      contactPhone: '+91 40 2401 5380',
      contactPerson: 'Dr. K. Anuradha (Senior Scientist)',
      distanceKm: 1.5,
      rating: 4.9,
    ),
    ChannelPartner(
      id: 'ptn_3',
      partnerName: 'State Bank of India',
      type: 'Bank',
      address: 'Gunfoundry, Abids, Hyderabad',
      latitude: 17.3940,
      longitude: 78.4780,
      contactPhone: '+91 40 2320 1200',
      contactPerson: 'Rajesh Sharma (Chief Manager)',
      distanceKm: 2.3,
      rating: 4.6,
    ),
  ];

  static List<ApplicationItem> get mockApplications => [
    ApplicationItem(
      id: 'app_1',
      trackingId: 'UDS-847291',
      userId: 'usr_demo',
      schemeId: 'sch_1',
      schemeName: 'PM Mudra Yojana',
      requestedAmount: 500000,
      proposedBusiness: 'South Indian Organic Canteen',
      status: 'Under Review',
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      remarks: 'Pre-screened by Udyam Setu Rule Engine (90% Match). Sent to Andhra Grameena Bank.',
      uploadedDocuments: [
        SchemeDocument(docName: 'Aadhaar Card', status: 'Uploaded'),
        SchemeDocument(docName: 'PAN Card', status: 'Uploaded'),
        SchemeDocument(docName: 'Business Plan', status: 'Pending'),
        SchemeDocument(docName: 'Bank Statement', status: 'Pending'),
        SchemeDocument(docName: 'Address Proof', status: 'Uploaded'),
      ],
    )
  ];
}
