name: udyam_setu
description: "AI-Driven Scheme Matching Platform for Marginalized Entrepreneurs (SIH PS ID: 92)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  speech_to_text: ^6.6.1
  url_launcher: ^6.2.4
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
